project:
  type: website
  output-dir: docs

website:
  title: "Possibly Significant"
  site-url: https://jarbet.github.io/possibly-significant/
  description: "A statistics and data science blog to test out new ideas, share R tutorials, and collect my thoughts. Perhaps you will find something significant here."

  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: rss
        href: index.xml
      - icon: house-fill
        href: https://jarbet.github.io/

format:
  html:
    theme: cosmo
    css: styles.css
