project:
  type: website
  output-dir: docs

website:
  description: "An informal stats blog for testing ideas, sharing short R tutorials, and collecting thoughts."
  site-url: https://jarbet.github.io/possibly-significant/
  title: "Possibly Significant"
  navbar:
    right:
      - icon: house-fill
        href: https://jarbet.github.io/

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: TRUE
    fig-number: TRUE
    fig-cap-location: margin
    embed-resources: true
    anchor-sections: TRUE
    code-tools: TRUE
    code-fold: FALSE
    toc: TRUE
    toc-open: true
    toc-depth: 3
    toc-location: left
    author:
    - name: Jaron Arbet

# Each post renders in its own directory using its own renv.lock file
execute:
  dir: file
  echo: false
  freeze: auto